#! /bin/sh

set -x

INTLTOOLIZE=`which intltoolize`
AUTORECONF=`which autoreconf`

if test -z $INTLTOOLIZE -o -z $AUTORECONF; then
	echo "Error: no intltoolize or autoreconf found, please install them" >&2
	exit 1
fi

$INTLTOOLIZE --copy --force --automake
$AUTORECONF --force --install --verbose
